version: "3.6"
services:
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword
  graphql-engine:
    image: hasura/graphql-engine:v2.8.4
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - "postgres"
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      # HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://fxpclrwokbiodm:076f2ca9a341c70449ae23c923084a90cef3cefadf5a3d425033061bfe1445bb@ec2-54-159-175-38.compute-1.amazonaws.com:5432/d2frlkkp2m8gj1
      ## this env var can be used to add the above postgres database to Hasura as a data source. this can be removed/updated based on your needs
      # PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://fxpclrwokbiodm:076f2ca9a341c70449ae23c923084a90cef3cefadf5a3d425033061bfe1445bb@ec2-54-159-175-38.compute-1.amazonaws.com:5432/d2frlkkp2m8gj1
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      ## uncomment next line to set an admin secret
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "HS256", "key": "z8pXvFrDjGWb3mRSJBAp9ZljHRnMofLF"}'
      # HASURA_GRAPHQL_ADMIN_SECRET: 03r1Xm9PYZ1pWvK5H06uhP5R23LP4sL4QTaiQaswcWJykqBOUhSFzx0g7CURXVqE
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  db_data:
