-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- CREATE OR REPLACE FUNCTION public.user_likes(recipe_row recipe, hasura_session json)
-- RETURNS boolean AS $$
-- SELECT EXISTS (
--     SELECT 1
--     FROM rating A
--     WHERE A.user_id = CAST((hasura_session ->> 'x-hasura-user-id') as uuid)  AND A.recipe_id = recipe_row.id
-- );
-- $$ LANGUAGE sql STABLE;
